name: Building Docker images for PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version from ref
        if: success()
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3-10 | tr '/' '-')

      - name: Build and push Docker base image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hellofreshtech/kangal-jmeter
          path: docker/jmeter-base/.
          tag_with_ref: true

      - name: Build and push Docker master image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hellofreshtech/kangal-jmeter-master
          path: docker/jmeter-master/.
          build_args: ${{ format('version=pr-{0}', steps.get_version.outputs.VERSION) }}
          tag_with_ref: true

      - name: Build and push Docker worker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hellofreshtech/kangal-jmeter-worker
          path: docker/jmeter-worker/.
          build_args: ${{ format('version=pr-{0}', steps.get_version.outputs.VERSION) }}
          tag_with_ref: true
