name: Building Release Docker images

on:
  release:
    types:
      - created

jobs:
  build_docker:
    name: Build docker image release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version from ref
        if: success()
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF)

      - name: Echo 1
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Build and push Docker base image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hellofreshtech/kangal-jmeter
          path: docker/jmeter-base/.
          tag_with_ref: true
          tags: latest

      - name: Build and push Docker master image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hellofreshtech/kangal-jmeter-master
          path: docker/jmeter-master/.
          build_args: ${{ format('version={0}', steps.get_version.outputs.VERSION) }}
          tag_with_ref: true
          tags: latest

      - name: Build and push Docker worker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hellofreshtech/kangal-jmeter-worker
          path: docker/jmeter-worker/.
          build_args: ${{ format('version={0}', steps.get_version.outputs.VERSION) }}
          tag_with_ref: true
          tags: latest
