name: Building Release Docker images

on:
  release:
    types:
      - created

jobs:
  build_docker:
    name: Build docker image release
    runs-on: ubuntu-latest
    env:
      JMETER_VERSION: "5.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version from ref
        if: success()
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: hellofreshtech
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker base image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{env.JMETER_VERSION}}
          tags: |
            hellofresh/kangal-jmeter:${{env.JMETER_VERSION}}
            hellofresh/kangal-jmeter:latest
          context: docker/jmeter-base
          file: docker/jmeter-base/Dockerfile
          push: true

      - name: Build and push Docker master image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{env.JMETER_VERSION}}
          tags: |
            hellofresh/kangal-jmeter-master:${{env.JMETER_VERSION}}
            hellofresh/kangal-jmeter-master:latest
          context: docker/jmeter-master
          file: docker/jmeter-master/Dockerfile
          push: true

      - name: Build and push Docker worker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{env.JMETER_VERSION}}
          tags: |
            hellofresh/kangal-jmeter-worker:${{env.JMETER_VERSION}}
            hellofresh/kangal-jmeter-worker:latest
          context: docker/jmeter-worker
          file: docker/jmeter-worker/Dockerfile
          push: true
