name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Setup Kube in Docker
        uses: engineerd/setup-kind@v0.4.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup latest Kangal release
        run: |
          mkdir kangal && cd kangal
          VERSION=$(curl -fsSL "https://api.github.com/repos/hellofresh/kangal/releases" | jq --raw-output 'map(select(.tag_name|startswith("kangal")|not))[0] | .tag_name')
          KANGAL_SOURCE_URL="https://github.com/hellofresh/kangal/archive/${VERSION}.tar.gz"
          curl -X GET -H "Accept:application/octet-stream" -fsSL "$KANGAL_SOURCE_URL" > "/tmp/kangal-source.tar.gz"
          tar -xzf "/tmp/kangal-source.tar.gz" -C /tmp
          mv "/tmp/kangal-${VERSION}"/* .
          make apply-crd
          sed -i "s/latest/local/" pkg/backends/jmeter/backend.go
          sed -i "s/Always/IfNotPresent/" pkg/backends/jmeter/resources.go
          make build

      - name: Build Docker base image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: hellofresh/kangal-jmeter
          tags: local
          path: docker/jmeter-base
          push: false

      - name: Build Docker master image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: hellofresh/kangal-jmeter-master
          tags: local
          path: docker/jmeter-master
          push: false
          build_args: VERSION=local

      - name: Build Docker worker image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: hellofresh/kangal-jmeter-worker
          tags: local
          path: docker/jmeter-worker
          push: false
          build_args: VERSION=local

      - name: Load docker images into kind cluster
        run: |
          docker images
          kind load docker-image hellofresh/kangal-jmeter-master:local
          kind load docker-image hellofresh/kangal-jmeter-worker:local

      - name: Run Integration Test
        env:
          AWS_ENDPOINT_URL: "localhost:8081"
          AWS_BUCKET_NAME: "kangal-test"
          JMETER_MASTER_IMAGE_NAME: "hellofresh/kangal-jmeter-master"
          JMETER_MASTER_IMAGE_TAG: "local"
          JMETER_WORKER_IMAGE_NAME: "hellofresh/kangal-jmeter-worker"
          JMETER_WORKER_IMAGE_TAG: "local"
        run: |
          cd kangal
          ./ci/integration-tests.sh
